Feat segurança acesso
Julio-Pupim/ServiceMaker pull request #41
Opened 2024-09-26 01:15 UTC by RafaelNogueira11

2024-09-26 01:22 UTC, Julio-Pupim requested changes

2024-09-26 01:22 UTC, Julio-Pupim commented on backend/src/main/java/br/com/servicemaker/controller/AutenticacaoController.java
> +    @Autowired
Rancar os autowirde e colocar o @allArgsConstructor na classe

2024-10-13 02:09 UTC, Julio-Pupim commented on backend/src/main/java/br/com/servicemaker/controller/AutenticacaoController.java
> +    public ResponseEntity login(@RequestBody @Valid AuthenticationDTO data) {
```suggestion
    public ResponseEntity<String>
```

2024-10-15 02:55 UTC, Julio-Pupim approved these changes

2024-10-17 22:06 UTC, Julio-Pupim approved these changes

2024-10-17 22:08 UTC, vrpmichels approved these changes

2024-10-17 22:08 UTC, merged